apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-api
  name: backend-api
  namespace: intellipaat
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30001
  selector:
    app: backend-api
  type: NodePort
