apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-ui
  name: frontend-ui
  namespace: intellipaat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
        - image: akilan/frontend-react:v1
          name: frontend-react
