apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-ui
  name: frontend-ui
  namespace: intellipaat
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30002
  selector:
    app: frontend-ui
  type: NodePort
